// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminAllowlist = __t.object("AdminAllowlist", {
  email: __t.string(),
  githubUsername: __t.string(),
});
export type AdminAllowlist = __Infer<typeof AdminAllowlist>;

export const AdminDailyVisits = __t.object("AdminDailyVisits", {});
export type AdminDailyVisits = __Infer<typeof AdminDailyVisits>;

export const AdminEstimates = __t.object("AdminEstimates", {});
export type AdminEstimates = __Infer<typeof AdminEstimates>;

export const AdminLifetimeVisits = __t.object("AdminLifetimeVisits", {});
export type AdminLifetimeVisits = __Infer<typeof AdminLifetimeVisits>;

export const AdminSession = __t.object("AdminSession", {
  identity: __t.identity(),
  connections: __t.u32(),
});
export type AdminSession = __Infer<typeof AdminSession>;

export const DailyVisit = __t.object("DailyVisit", {
  date: __t.string(),
  total: __t.u64(),
  adminScope: __t.string(),
});
export type DailyVisit = __Infer<typeof DailyVisit>;

export const EstimateRequest = __t.object("EstimateRequest", {
  id: __t.u64(),
  name: __t.string(),
  email: __t.string(),
  phone: __t.string(),
  service: __t.string(),
  location: __t.string(),
  description: __t.string(),
  preferredContact: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  status: __t.string(),
  adminNotes: __t.string(),
  adminScope: __t.string(),
});
export type EstimateRequest = __Infer<typeof EstimateRequest>;

export const GatewayIdentity = __t.object("GatewayIdentity", {
  identity: __t.identity(),
});
export type GatewayIdentity = __Infer<typeof GatewayIdentity>;

export const LifetimeVisit = __t.object("LifetimeVisit", {
  key: __t.u8(),
  total: __t.u64(),
  adminScope: __t.string(),
});
export type LifetimeVisit = __Infer<typeof LifetimeVisit>;

export const MigrationState = __t.object("MigrationState", {
  key: __t.u8(),
  legacyTotalImported: __t.bool(),
});
export type MigrationState = __Infer<typeof MigrationState>;

export const ModuleOwner = __t.object("ModuleOwner", {
  identity: __t.identity(),
});
export type ModuleOwner = __Infer<typeof ModuleOwner>;

export const SecurityConfig = __t.object("SecurityConfig", {
  key: __t.u8(),
  oidcAudience: __t.string(),
});
export type SecurityConfig = __Infer<typeof SecurityConfig>;

