// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChangeEstimateStatusReducer from "../change_estimate_status_reducer";
import ConfigureSecurityReducer from "../configure_security_reducer";
import CreateEstimateReducer from "../create_estimate_reducer";
import ImportLegacyVisitTotalReducer from "../import_legacy_visit_total_reducer";
import OnConnectReducer from "../on_connect_reducer";
import OnDisconnectReducer from "../on_disconnect_reducer";
import RecordVisitReducer from "../record_visit_reducer";
import UpdateEstimateNotesReducer from "../update_estimate_notes_reducer";

export type ChangeEstimateStatusParams = __Infer<typeof ChangeEstimateStatusReducer>;
export type ConfigureSecurityParams = __Infer<typeof ConfigureSecurityReducer>;
export type CreateEstimateParams = __Infer<typeof CreateEstimateReducer>;
export type ImportLegacyVisitTotalParams = __Infer<typeof ImportLegacyVisitTotalReducer>;
export type OnConnectParams = __Infer<typeof OnConnectReducer>;
export type OnDisconnectParams = __Infer<typeof OnDisconnectReducer>;
export type RecordVisitParams = __Infer<typeof RecordVisitReducer>;
export type UpdateEstimateNotesParams = __Infer<typeof UpdateEstimateNotesReducer>;

