/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false --strict-vars=false worker/worker-configuration.d.ts` (hash: 8d70a5e39110b3446dc30b24fe14e828)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: string;
	TURNSTILE_HOSTNAMES: string;
	TURNSTILE_TEST_MODE: string;
	SPACETIMEDB_BASE_URL: string;
	SPACETIMEDB_DATABASE: string;
	TURNSTILE_SECRET: string;
	SPACETIMEDB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "TURNSTILE_HOSTNAMES" | "TURNSTILE_TEST_MODE" | "SPACETIMEDB_BASE_URL" | "SPACETIMEDB_DATABASE" | "TURNSTILE_SECRET" | "SPACETIMEDB_TOKEN">> {}
}
