/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false --strict-vars=false worker/worker-configuration.d.ts` (hash: 4f083b27f84a64d44945326d210f2782)
interface __BaseEnv_Env {
	DB: D1Database;
	ALLOWED_ORIGINS: string;
	ADMIN_HOSTNAMES: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	ADMIN_EMAIL: string;
	LOCAL_ADMIN_BYPASS?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface LocalEnv {
		DB: D1Database;
		ALLOWED_ORIGINS: string;
		ADMIN_HOSTNAMES: string;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		ADMIN_EMAIL: string;
		LOCAL_ADMIN_BYPASS: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "ADMIN_HOSTNAMES" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "ADMIN_EMAIL" | "LOCAL_ADMIN_BYPASS">> {}
}
