/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --include-runtime=false --strict-vars=false worker/worker-configuration.d.ts` (hash: 2ab2cb163e6d96f52bb669ce0f08e489)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: string;
	SPACETIMEDB_BASE_URL: string;
	SPACETIMEDB_DATABASE: string;
	SPACETIMEDB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "SPACETIMEDB_BASE_URL" | "SPACETIMEDB_DATABASE" | "SPACETIMEDB_TOKEN">> {}
}
